CREATE TABLE `payorder` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_guid` int(11) NOT NULL,
  `goods_guid` varchar(128) NOT NULL DEFAULT '',
  `goods_type` varchar(128) NOT NULL DEFAULT '',
  `goods_num` int(11) NOT NULL DEFAULT '1',
  `order_id` varchar(64) NOT NULL DEFAULT '',
  `order_title` varchar(100) NOT NULL,
  `actual_price` decimal(10,2) NOT NULL,
  `payment_status` int(11) NOT NULL DEFAULT '0',
  `payment_order` varchar(128) DEFAULT '',
  `payment_info` text,
  `invoice_info` text,
  `payment_method` varchar(128) DEFAULT '',
  `created_at` varchar(64) NOT NULL DEFAULT '',
  `updated_at` varchar(64) NOT NULL DEFAULT '',
  `expired_time` int(11) DEFAULT NULL,
  `payment_time` int(11) DEFAULT NULL,
  `invoicing_status` int(11) NOT NULL DEFAULT '0',
  `refund_status` int(11) NOT NULL DEFAULT '0',
  `address_id` int(11) DEFAULT NULL,
  `is_transported` enum('1','0') DEFAULT '0',
  `transportation_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UID_OID` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;